#!/usr/bin/env python

from boto import ec2
import sys, getopt, re



def main():

    try:
        opts, args = getopt.getopt(sys.argv[1:], "hs:a:k:d", ["help", "snaps=", "amis=", "keep="])
    except getopt.GetoptError as err:
        print(err)
        usage()
        sys.exit(2)

    snaps = None
    imags = None
    keep  = 0
    dry_run = False

    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-s", "--snaps"):
            snaps = a
        elif o in ("-a", "--amis"):
            imags = a
        elif o in ("-k", "--keep"):
            keep = int(a)
        elif o in ("-d"):
            dry_run = True
            print "Dry run specified.  Nothing will change."
        else:
            assert False, "unhandled option"

    if len(sys.argv) < 2:
        usage()
        sys.exit()

    connection=ec2.connect_to_region('us-east-1')


    # Process snaps:
    if snaps != None:

        snapshots=connection.get_all_snapshots(filters={'description':snaps})

        count = keep
    
        for snaps in snapshots:
            count-=1
  
            if count < 0:
                print "Deleting: " + snaps.id , "-" , snaps.start_time , "-" , snaps.volume_size , "\n"
                delete_snaps(connection, snaps.id, dry_run)

    # Process images:
    if imags != None:
        count = keep

        images = connection.get_all_images(owners='self', filters={"tag:Name" : imags})

        for image in images:
            count-=1

            if count < 0:
                print "Deleting: " + image.id , ", along with corresponding snapshot..."
                delete_amis(connection, image.id, dry_run)

def delete_snaps(connection, snapshot, dry_run=False):

    try:
        connection.delete_snapshot(snapshot, dry_run)
    except Exception as e:
        print str(e)
    return

def delete_amis(connection, ami, dry_run=False):

    try:
        connection.deregister_image(ami, True, dry_run)
    except Exception as e:
        print str(e)

    return

def usage():
    print '''
USAGE:

--keep 

  "keep last 'n'"; where n is an integer

--snaps
  
  "a regex to match snaps"

--amis

  " a regex to match amis"

    ./clean --snaps 'jenkins-ebs-snapshot-*' --keep 10

    ./clean --amis 'kube_slave*' --keep 10

'''

if __name__ == "__main__":
    main()
