#!/usr/bin/env python

from boto import ec2
import sys, getopt, re



def main():

    try:
        opts, args = getopt.getopt(sys.argv[1:], "hs:a:k:", ["help", "snaps=", "amis=", "keep="])
    except getopt.GetoptError as err:
        print(err)
        usage()
        sys.exit(2)

    snaps = None
    amis  = False
    keep  = 0

    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-s", "--snaps"):
            snaps = a
        elif o in ("-a", "--amis"):
            amis = a
        elif o in ("-k", "--keep"):
            keep = int(a)
        else:
            assert False, "unhandled option"

    if len(sys.argv) < 2:
        usage()
        sys.exit()

    connection=ec2.connect_to_region('us-east-1')
    snapshots=connection.get_all_snapshots(filters={'description':snaps})

    count = keep

    for snaps in snapshots:
        count-=1

        if count < 0:
            print "Deleting: " + snaps.id , "-" , snaps.start_time , "-" , snaps.volume_size , "\n"
            connection.delete_snapshot(snaps.id, False)

def usage():
    print '''
USAGE:

    clean snaps "jenkins"

'''

if __name__ == "__main__":
    main()
