#!/usr/bin/env python


import boto3, json, sys
import ConfigParser, getopt

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.GetoptError as err:
        print str(err)
        usage()
        sys.exit(2)


    for o, a in opts:
        if o == "-h":
            usage()
            sys.exit()
        else:
            assert False, "unhandled option"

    if len(sys.argv) < 2:
        usage()
        sys.exit()
    else:
        file = sys.argv[1]

    config = ConfigParser.ConfigParser()
    config.readfp(open(file))
    print config.sections()

def usage():
    print '''
    USAGE:

      ./tag_aws filename
    '''

if __name__ == "__main__":
    main()
